module.exports = [
    { id: 1, fullName: 'Oleh Lev', position: 'Web Dev', skill: 'PHP,JS', exp: 3, gender: 'Male', salary: 4500 },
    { id: 2, fullName: 'John White', position: 'Web Dev', skill: 'PHP', exp: 1, gender: 'Male', salary: 1200 },
    { id: 3, fullName: 'Jany Rad', position: 'Sale', skill: '-', exp: 2, gender: 'Female', salary: 3500 },
    { id: 4, fullName: 'Ivan Brown', position: 'iOS', skill: 'Swift', exp: 3, gender: 'Male', salary: 4000 },
    { id: 5, fullName: 'Pet Bool', position: 'Android', skill: 'Java', exp: 2, gender: 'Male', salary: 3520 },
    { id: 6, fullName: 'Emma Hallo', position: 'Android', skill: 'Kotlin', exp: 1, gender: 'Female', salary: 2520 },
    { id: 7, fullName: 'Olivia Jones', position: 'iOS', skill: 'Objective-C', exp: 3, gender: 'Female', salary: 2820 },
    { id: 8, fullName: 'William Smith', position: 'Designer', skill: '-', exp: 5, gender: 'Male', salary: 3000 },
    { id: 9, fullName: 'Oliver Alien', position: 'PM', skill: '-', exp: 4, gender: 'Male', salary: 6000 },
    { id: 10, fullName: 'Joseph Jason', position: 'Web Dev', skill: 'PHP', exp: 2, gender: 'Male', salary: 2100 },
    { id: 11, fullName: 'Alex Rosso', position: 'Web Dev', skill: 'PHP', exp: 2, gender: 'Male', salary: 2050 },
    { id: 12, fullName: 'Chris Mirt', position: 'Designer', skill: '-', exp: 1, gender: 'Male', salary: 1000 },
    { id: 13, fullName: 'Caleb Grace', position: 'iOS', skill: 'Objective-C', exp: 2, gender: 'Male', salary: 3000 },
    { id: 14, fullName: 'Daniel Aria', position: 'Sale', skill: '-', exp: 3, gender: 'Female', salary: 2100 },
    { id: 15, fullName: 'Luke Ava', position: 'Web Dev', skill: 'PHP,JS', exp: 3, gender: 'Male', salary: 3100 },
    { id: 16, fullName: 'Carter Melissa', position: 'Web Dev', skill: 'PHP,JS', exp: 2, gender: 'Male', salary: 2900 },
    { id: 17, fullName: 'Eric Ashley', position: 'iOS', skill: 'Objective-C', exp: 3, gender: 'Male', salary: 3000 },
    { id: 18, fullName: 'Todd Karen', position: 'Web Dev', skill: 'PHP', exp: 2, gender: 'Male', salary: 1800 },
    { id: 19, fullName: 'Ronald Dawn', position: 'Android', skill: 'Java', exp: 2, gender: 'Male', salary: 3000 },
    { id: 20, fullName: 'Mia Morris', position: 'Owner', skill: '-', exp: 10, gender: 'Female', salary: 10000 },
];
